esphome:
  name: port-esp32
  friendly_name: port-esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WOPkGzhXeXCL7z+IRO5/Kz0Sk48tjMKSr/jWDPDPI0Y="

ota:
  - platform: esphome
    password: "a935611cbbe3e1cc775fb8f4abdc29ee"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Port-Esp32 Fallback Hotspot"
    password: "44zKUbExqCk5"

i2c:
  sda: 21
  scl: 22
  scan: False
  id: bus_a

captive_portal:

web_server:
  port: 80
  include_internal: False

time:
  - platform: homeassistant
    id: homeassistant_time

ads1115:
  - address: 0x48

sensor:
  - platform: ads1115
    id: se_close
    multiplexer: 'A0_GND'
    gain: 4.096
    update_interval: 0.2s
    name: "Kantliste V luk"
    disabled_by_default: True
    filters:
      - or:
        - throttle: 60s
        - delta: 0.1
  - platform: ads1115
    id: se_open
    multiplexer: 'A1_GND'
    gain: 4.096
    update_interval: 0.2s
    name: "Kantliste V åben"
    disabled_by_default: True
    filters:
      - or:
        - throttle: 60s
        - delta: 0.1

  - platform: resistance
    sensor: se_close
    icon: "mdi:omega"
    configuration: DOWNSTREAM
    resistor: 10.1kOhm
    name: Kantliste modstand luk
    reference_voltage: 3.3
  - platform: resistance
    sensor: se_open
    icon: "mdi:omega"
    configuration: DOWNSTREAM
    resistor: 10.1kOhm
    name: Kantliste modstand åben
    reference_voltage: 3.3


binary_sensor:
  - platform: gpio
    device_class: door
    pin:
      number: 17
      inverted: False
      mode:
        input: true
        pullup: true
    name: "Port status"
  - platform: gpio
    device_class: occupancy
    icon: "mdi:motion-sensor"
    pin:
      number: 19
      inverted: False
    name: "Fotocelle"
  - platform: gpio
    pin:
      number: 16
      inverted: True
    name: "Open signal input"
  - platform: gpio
    device_class: occupancy
    icon: "mdi:alert"
    pin:
      number: 18
      inverted: True
    name: "Nødstop"

  - platform: template
    name: "Kantliste tilstand åben"
    device_class: occupancy
    icon: "mdi:arrow-collapse-horizontal"
    lambda: |-
      if (id(se_open).state < 1 or id(se_open).state > 2){
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Kantliste tilstand luk"
    device_class: occupancy
    icon: "mdi:arrow-collapse-horizontal"
    lambda: |-
      if (id(se_close).state < 1 or id(se_close).state > 2){
        return true;
      } else {
        return false;
      }


switch:
  - platform: gpio
    pin: 
      number: 2
      inverted: True
    name: "Port åben"
    icon: "mdi:gate"


  - platform: restart
    name: "Genstart port esp32"
