esphome:
  name: port-esp8266
  friendly_name: port-esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Port-Esp8266 Fallback Hotspot"
    password: ""

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    device_class: door
    pin:
      number: GPIO16
      inverted: False
    name: "Port status"

switch:
  - platform: gpio
    pin: GPIO5
    id: relay
    name: "Port"
    icon: "mdi:gate"
#    on_turn_on:
#    - delay: 500ms
#    - switch.turn_off: relay

  - platform: restart
    name: "Genstart port esp8266"
